### ISSUE TITLE
一次性给混合语言项目创建索引

### ISSUE THREAD

**Issue by wuxianliang** [allwefantasy/auto-coder#29]
我在做一个前端vue.js后端python的项目，参考文档
[008-如何支持各种语言的项目](https://github.com/allwefantasy/auto-coder/blob/master/docs/zh/008-AutoCoder%20%E5%A6%82%E4%BD%95%E6%94%AF%E6%8C%81%E5%90%84%E7%A7%8D%E8%AF%AD%E8%A8%80%E7%9A%84%E9%A1%B9%E7%9B%AE.md)
[029-AutoCoder_混合项目如何开发](https://github.com/allwefantasy/auto-coder/blob/master/docs/zh/029AutoCoder_%E6%B7%B7%E5%90%88%E9%A1%B9%E7%9B%AE%E5%A6%82%E4%BD%95%E5%BC%80%E5%8F%91.md)
我理解在给已有代码第一次创建索引的时候，我在auto-coder.chat中运行/index/build命令，此时我的base.yml是
```yaml
project_type: .py, .js, .vue
source_dir: /home/wxl/stocks
target_file: /home/wxl/stocks/output.txt

model: deepseekchat
model_max_length: 3000
model_max_input_length: 200000
anti_quota_limit: 1

execute: true
human_as_model: false
```
我发现auto-coder只给第一个文件类型构建索引，于是我只能手动给每一个文件类型构建索引。
我希望auto-coder能够自动依次构建所有语言的文件索引
